name: run-app-tests

on: [pull_request, push]

jobs:
  check:
    needs: check-commit-messages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ”
        uses: actions/checkout@v2
      - name: Setup Node & Test App ğŸ¨
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test -u
